import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,applyAction,BOARD,actor,rent,canBuild,canSell,projectGame,validSavedGame} from '../web/engine.js';
import {botStep,chooseAction} from '../web/ai.js';
const fresh=(n=3)=>createGame({playerCount:n,mode:'local'},()=>.1);
const set=(g,ids,owner,level=0)=>{for(const id of ids)g.properties[id]={owner,level,mortgaged:false};};
const act=(g,a,rng=()=>.3)=>applyAction(g,actor(g),a,rng);
function invariant(g){
  const houses=g.properties.reduce((s,p)=>s+(p&&p.level<5?p.level:0),0),hotels=g.properties.filter(p=>p?.level===5).length;
  assert.equal(g.houses+houses,32);assert.equal(g.hotels+hotels,12);
  for(const p of g.players){assert.ok(Number.isSafeInteger(p.cash)&&p.cash>=0);assert.ok(p.pos>=0&&p.pos<40);if(p.bankrupt)assert.ok(!g.properties.some(x=>x?.owner===p.id));}
  for(const key of ['chance','chest']){const cards=[...g.decks[key],...g.players.flatMap(p=>p.cards.filter(c=>c.deck===key).map(c=>c.index))];assert.equal(cards.length,16);assert.equal(new Set(cards).size,16);}
}
test('board economics, inventory and projection hide future cards',()=>{const g=fresh();assert.equal(BOARD.length,40);assert.equal(g.properties.filter(Boolean).length,28);assert.equal(g.players[0].cash,15000);invariant(g);assert.ok(validSavedGame(g));assert.equal(projectGame(g).decks,undefined);assert.equal(projectGame(g).queue,undefined);assert.ok(!validSavedGame({schema:1}));});
test('a turn rolls exactly one die and six never grants an extra roll',()=>{let g=fresh(),calls=0;g.players[0].pos=14;g=act(g,{type:'roll'},()=>{calls++;return .99;});assert.equal(calls,1);assert.deepEqual(g.dice,[6]);assert.equal(g.players[0].pos,20);assert.equal(g.extra,false);assert.throws(()=>act(g,{type:'roll'}));g=act(g,{type:'end'});assert.equal(g.turn,1);assert.equal(g.phase,'roll');});
test('passing GO pays once and unowned property opens purchase',()=>{let g=fresh();g.players[0].pos=39;g=act(g,{type:'roll'},()=>.2);assert.equal(g.players[0].pos,1);assert.equal(g.players[0].cash,17000);assert.equal(g.phase,'buy');});
test('declining landed property leaves it unowned until another player lands and buys',()=>{let g=act(fresh(),{type:'roll'},()=>0);assert.equal(g.pending,1);const balances=g.players.map(p=>p.cash);g=act(g,{type:'skipBuy'});assert.equal(g.phase,'end');assert.equal(g.pending,null);assert.equal(g.auction,null);assert.equal(g.properties[1].owner,null);assert.deepEqual(g.players.map(p=>p.cash),balances);assert.throws(()=>act(g,{type:'buy'}));g=act(g,{type:'end'});g=act(g,{type:'roll'},()=>0);assert.equal(g.pending,1);g=act(g,{type:'buy'});assert.equal(g.properties[1].owner,1);assert.equal(g.players[1].cash,14400);assert.equal(g.players[0].cash,15000);assert.equal(g.phase,'end');});
test('only the landed player can buy or skip and obsolete auction actions are rejected',()=>{const g=act(fresh(),{type:'roll'},()=>0),before=structuredClone(g);for(const type of ['buy','skipBuy'])assert.throws(()=>applyAction(g,1,{type}),/轮到你/);for(const type of ['auction','bid','pass'])assert.throws(()=>act(g,{type,amount:100}));assert.deepEqual(g,before);g.players[0].cash=0;assert.throws(()=>act(g,{type:'buy'}),/现金不足/);assert.deepEqual(chooseAction(g),{type:'skipBuy'});assert.equal(botStep(g).phase,'end');});
test('color-set rent, even building and hotels conserve physical inventory',()=>{let g=fresh();set(g,[1,3],0);g.phase='end';g.players[0].pos=1;assert.equal(rent(g,1),40);g=act(g,{type:'build',property:1});assert.equal(canBuild(g,0,1),false);for(const at of [3,1,3,1,3,1,3,1]){g.players[0].pos=at;g=act(g,{type:'build',property:at});}assert.equal(g.properties[1].level,5);assert.equal(g.houses,28);assert.equal(g.hotels,11);assert.equal(rent(g,1),2500);g=act(g,{type:'sell',property:1});assert.equal(g.properties[1].level,4);invariant(g);});
test('hotel downgrade blocked without houses, full group sale releases hotels',()=>{let g=fresh();set(g,[1,3],0,5);g.hotels=10;set(g,[6,8,9,11,13,14,16,18],1,4);g.houses=0;assert.ok(!canSell(g,0,1));g=act(g,{type:'sellGroup',property:1});assert.equal(g.players[0].cash,17500);assert.equal(g.hotels,12);invariant(g);});
test('mortgage requires all group buildings sold; redemption charges 10%',()=>{let g=fresh();set(g,[1,3],0);g.phase='end';g.players[0].pos=1;g=act(g,{type:'build',property:1});assert.throws(()=>act(g,{type:'mortgage',property:3}));g=act(g,{type:'sell',property:1});g=act(g,{type:'mortgage',property:1});assert.equal(rent(g,1),0);assert.equal(rent(g,3),80);const cash=g.players[0].cash;g=act(g,{type:'redeem',property:1});assert.equal(g.players[0].cash,cash-330);});
test('third failed jail roll resolves fee debt before moving',()=>{let g=fresh();g.players[0].jail=true;g.players[0].jailTurns=2;g.players[0].pos=10;g.players[0].cash=200;set(g,[1],0);g=act(g,{type:'roll'},()=>.34);assert.equal(g.phase,'debt');assert.equal(g.players[0].pos,10);g=act(g,{type:'mortgage',property:1});assert.equal(g.players[0].pos,13);assert.equal(g.players[0].cash,0);assert.equal(g.phase,'buy');assert.equal(g.extra,false);});
test('jail releases on six without granting another roll',()=>{let g=fresh();g.players[0].jail=true;g.players[0].pos=10;g=act(g,{type:'roll'},()=>.99);assert.equal(g.extra,false);assert.equal(g.players[0].jail,false);assert.equal(g.players[0].pos,16);assert.deepEqual(g.dice,[6]);});
test('trade confirmation changes ownership atomically and charges mortgage fee',()=>{let g=fresh();set(g,[1],0);set(g,[6],1);g.properties[6].mortgaged=true;g=act(g,{type:'trade',to:1,give:[1],take:[6],giveCash:500,takeCash:0});assert.equal(actor(g),1);assert.throws(()=>applyAction(g,2,{type:'acceptTrade'}));g=act(g,{type:'acceptTrade'});assert.equal(g.properties[6].owner,0);assert.equal(g.players[0].cash,14450);assert.equal(g.players[1].cash,15500);assert.equal(g.phase,'roll');});
test('reject trade leaves economic state unchanged; malformed or built-property offers rejected',()=>{let g=fresh();set(g,[1,3],0);g=act(g,{type:'trade',to:1,give:[1],take:[],giveCash:0,takeCash:1000});g=act(g,{type:'rejectTrade'});assert.equal(g.properties[1].owner,0);g.phase='end';g.players[0].pos=1;g=act(g,{type:'build',property:1});assert.throws(()=>act(g,{type:'trade',to:1,give:[3],take:[]}));assert.throws(()=>act(g,{type:'trade',to:1,giveCash:-10}));});
test('rent debt cannot be voluntarily abandoned while liquid assets suffice',()=>{let g=fresh();g.players[0].cash=50;set(g,[1],0);set(g,[6],1);g.players[0].pos=3;g=act(g,{type:'roll'},()=>.34);assert.equal(g.phase,'debt');assert.throws(()=>act(g,{type:'bankrupt'}));g=act(g,{type:'mortgage',property:1});assert.equal(g.players[0].cash,290);assert.equal(g.players[1].cash,15060);assert.equal(g.phase,'end');});
test('bankruptcy to bank returns unmortgaged unowned property without an auction',()=>{let g=fresh();g.players[0].cash=0;g.phase='debt';g.debt={kind:'pay',from:0,to:null,amount:2000};set(g,[1],0);g.properties[1].mortgaged=true;g=act(g,{type:'bankrupt'});assert.equal(g.players[0].bankrupt,true);assert.equal(g.properties[1].owner,null);assert.equal(g.properties[1].mortgaged,false);assert.equal(g.auction,null);assert.equal(g.turn,1);assert.equal(g.phase,'roll');g=act(g,{type:'roll'},()=>0);g=act(g,{type:'buy'});assert.equal(g.properties[1].owner,1);});
test('bankruptcy transfers mortgages and triggers creditor fees without exposing future decks',()=>{let g=fresh();g.phase='debt';g.debt={kind:'pay',from:0,to:1,amount:5000};g.players[0].cash=0;g.players[1].cash=0;set(g,[39],0);g.properties[39].mortgaged=true;g=act(g,{type:'bankrupt'});assert.equal(g.properties[39].owner,1);assert.equal(g.phase,'debt');assert.equal(g.debt.from,1);assert.equal(g.debt.amount,200);g=act(g,{type:'bankrupt'});assert.equal(g.phase,'finished');assert.equal(g.winner,2);});
test('birthday card can require another player to liquidate, then resumes card owner',()=>{let g=fresh();g.players[0].pos=14;g.players[1].cash=0;set(g,[1],1);g.decks.chest=[8,...g.decks.chest.filter(i=>i!==8)];g=act(g,{type:'roll'},()=>.34);assert.equal(g.phase,'debt');assert.equal(actor(g),1);g=act(g,{type:'mortgage',property:1});assert.equal(g.turn,0);assert.equal(g.phase,'end');assert.equal(g.players[0].cash,15200);});
test('AI uses only projected public information',()=>{const g=fresh();assert.deepEqual(chooseAction(g),chooseAction(projectGame(g)));});
test('redemption uses integer arithmetic: mortgage 500 costs exactly 550',()=>{let g=fresh();set(g,[8],0);g=act(g,{type:'mortgage',property:8});const before=g.players[0].cash;g=act(g,{type:'redeem',property:8});assert.equal(before-g.players[0].cash,550);});
test('100 seeded complete games preserve money/inventory/card invariants',()=>{for(let seed=1;seed<=100;seed++){let n=seed;const rng=()=>((n=Math.imul(n,1664525)+1013904223>>>0)/2**32);let g=createGame({playerCount:2+seed%5},rng),i=0;for(;i<15000&&g.phase!=='finished';i++){g=botStep(g,rng);invariant(g);}assert.equal(g.phase,'finished',`seed ${seed} stuck at ${g.phase}`);assert.equal(g.players.filter(p=>!p.bankrupt).length,1);}});
test('mortgaged deed sale pays seller, charges transfer fee, and requires separate redemption',()=>{
  let g=fresh();set(g,[8],0);g=act(g,{type:'mortgage',property:8});assert.equal(g.players[0].cash,15500);assert.equal(rent(g,8),0);
  g=act(g,{type:'trade',to:1,give:[8],take:[],giveCash:0,takeCash:800});g=act(g,{type:'acceptTrade'});
  assert.equal(g.players[0].cash,16300);assert.equal(g.players[1].cash,14150);assert.equal(g.properties[8].owner,1);assert.equal(g.properties[8].mortgaged,true);assert.equal(rent(g,8),0);
  g=act(g,{type:'roll'},()=>.99);g=act(g,{type:'skipBuy'});g=act(g,{type:'end'});g=act(g,{type:'redeem',property:8});
  assert.equal(g.players[1].cash,13600);assert.equal(g.properties[8].mortgaged,false);assert.equal(rent(g,8),60);
});
